const ItemData = [
  {
    ITEMCODE: "KCLI",
    DESCRIPTION: "Apt 1129",
    GROUP: "Red",
    TYPE: "Nissan",
    fpcs: 4,
    fweight: 45.168,
    Detail: "14th Floor",
    Rate:896.23,
    Rate_Type: "Yellow",
    Percentage: 7.89,
    Brand: "GT-R",
    ITEM_TYPE: "visa-electron",
    LOOSE_STONE: 4,
    Silver: 9.528,
    CompanyCode: "Tagopia",
  },
  {
    ITEMCODE: "PAIM",
    DESCRIPTION: "Suite 44",
    GROUP: "Yellow",
    TYPE: "Chevrolet",
    fpcs: 2,
    fweight: 59.245,
    Detail: "15th Floor",
    Rate: 9832.23,
    Rate_Type: "Blue",
    Percentage: 1.11,
    Brand: "TrailBlazer",
    ITEM_TYPE: "mastercard",
    LOOSE_STONE: 5,
    Silver: 8.111,
    CompanyCode: "Bubblemix",
  },
  {
    ITEMCODE: "UOHH",
    DESCRIPTION: "14th Floor",
    GROUP: "Green",
    TYPE: "Chevrolet",
    fpcs: 4,
    fweight: 93.084,
    Detail: "Room 1930",
    Rate: 9632.58,
    Rate_Type: "Goldenrod",
    Percentage: 10.24,
    Brand: "G-Series G20",
    ITEM_TYPE: "mastercard",
    LOOSE_STONE: 10,
    Silver: 4.096,
    CompanyCode: "Voonyx",
  },
  {
    ITEMCODE: "SBEG",
    DESCRIPTION: "Room 1726",
    GROUP: "Blue",
    TYPE: "Volvo",
    fpcs: 5,
    fweight: 48.036,
    Detail: "PO Box 73497",
    Rate:968.23,
    Rate_Type: "Aquamarine",
    Percentage: 16.69,
    Brand: "XC90",
    ITEM_TYPE: "jcb",
    LOOSE_STONE: 3,
    Silver: 9.879,
    CompanyCode: "Gigabox",
  },
  {
    ITEMCODE: "UASP",
    DESCRIPTION: "4th Floor",
    GROUP: "Orange",
    TYPE: "Chevrolet",
    fpcs: 4,
    fweight: 96.58,
    Detail: "8th Floor",
    Rate:700.32,
    Rate_Type: "Teal",
    Percentage: 15.45,
    Brand: "Avalanche 2500",
    ITEM_TYPE: "jcb",
    LOOSE_STONE: 1,
    Silver: 1.027,
    CompanyCode: "Yodel",
  },
  {
    ITEMCODE: "AYBU",
    DESCRIPTION: "Room 1757",
    GROUP: "Fuscia",
    TYPE: "GMC",
    fpcs: 6,
    fweight: 72.655,
    Detail: "Suite 13",
    Rate: 89.36,
    Rate_Type: "Purple",
    Percentage: 13.67,
    Brand: "Yukon XL 2500",
    ITEM_TYPE: "instapayment",
    LOOSE_STONE: 7,
    Silver: 7.886,
    CompanyCode: "Vipe",
  },
  {
    ITEMCODE: "PAYEL",
    DESCRIPTION: "Room 242",
    GROUP: "Orange",
    TYPE: "Dodge",
    fpcs: 4,
    fweight: 82.982,
    Detail: "16th Floor",
    Rate: 69.36,
    Rate_Type: "Indigo",
    Percentage: 19.42,
    Brand: "Journey",
    ITEM_TYPE: "jcb",
    LOOSE_STONE: 9,
    Silver: 4.484,
    CompanyCode: "Camido",
  },
  {
    ITEMCODE: "KBVS",
    DESCRIPTION: "Suite 27",
    GROUP: "Maroon",
    TYPE: "Mazda",
    fpcs: 3,
    fweight: 11.208,
    Detail: "Room 777",
    Rate:89658.36,
    Rate_Type: "Pink",
    Percentage: 6.99,
    Brand: "MX-5",
    ITEM_TYPE: "switch",
    LOOSE_STONE: 7,
    Silver: 8.383,
    CompanyCode: "Vidoo",
  },
  {
    ITEMCODE: "MMIO",
    DESCRIPTION: "Room 123",
    GROUP: "Indigo",
    TYPE: "Nissan",
    fpcs: 9,
    fweight: 15.736,
    Detail: "PO Box 65085",
    Rate: 98663.36,
    Rate_Type: "Green",
    Percentage: 1.03,
    Brand: "Xterra",
    ITEM_TYPE: "jcb",
    LOOSE_STONE: 6,
    Silver: 9.429,
    CompanyCode: "Skaboo",
  },
  {
    ITEMCODE: "KBBP",
    DESCRIPTION: "Suite 14",
    GROUP: "Puce",
    TYPE: "Mitsubishi",
    fpcs: 2,
    fweight: 91.576,
    Detail: "Suite 96",
    Rate:8965.36,
    Rate_Type: "Mauv",
    Percentage: 13.74,
    Brand: "Pajero",
    ITEM_TYPE: "mastercard",
    LOOSE_STONE: 7,
    Silver: 4.507,
    CompanyCode: "Miboo",
  },
];

export default ItemData;
